### ISSUE TITLE
Installing man pages

### ISSUE THREAD

**Issue by bdubbs** [gentoo/eudev#109]
Using the new eudev-3.0 tarball, I see the pre-built man pages are present.  That is very good.  Thanks.  It is helpful for LFS.  

However there is a minor install issue.  The man pages are not installed as a part of 'make install'.  Granted, the only thing that needs to be done is 

pushd man; make install-man7 install-man8; popd

But it would be nice if that was done as a part of 'make install'

**Comment by blueness** [comment]
agreed i'll definitely have it fixed for the next release.

**Comment by blueness** [comment]
the problem was AC_ARG_ENABLE([manpages],...) was wrong so that both --disable-manpages and --enable-manpages would disable them, while giving no option would enable them.  This has been fixed, with the default being --disable-manpages if no option is given.

The fix is commit 047416ff0f9ea822d6fdc3dabb4039f2ebcdab77
