### ISSUE TITLE
Version compatibility mapping between eudev and udev

### ISSUE THREAD

**Issue by anto** [gentoo/eudev#115]
Dear eudev maintainers,

I am quite new to eudev as I have just started to try it on my Debian wheezy install. So I am sorry if this shall be quite obvious. But I fail to find information about the version compatibility mapping between eudev and udev. Due to the versions differences between eudev and udev, this information is especially important when we need to compile packages requiring udev, so that we know which eudev version we should use.

Is there such information recorded somewhere in this repository or on Gentoo site? If so, could you please let me know that?

If that information is recorded somewhere else, I think it would be better to also add it into this repository so that it will be included in the distribution of eudev.

Thanks in advance.

Anto

**Comment by blueness** [comment]
Take a look at the top few lines of configure.ac:

<pre>
AC_PREREQ([2.68])
AC_INIT([eudev],[3.0],[https://github.com/gentoo/eudev/issues])
AC_SUBST(UDEV_VERSION, 219)
AC_CONFIG_SRCDIR([src/udev/udevd.c])
</pre>

Hoever this information is only really in sync for a release.  On git head you should read this more as eudev version 3.0+ = udev verison 219+ where the + means "that release plus all other commits since."

I hope this helps and let me know any other info yo may need to get a clean deb pkg going.

**Comment by anto** [comment]
Thanks blueness. I knew that it must be that obvious, but I failed to look at it. :)

I am using your eudev on my PC that I am using now to write this comment, which is still running using mostly Debian wheezy packages. It is still at eudev 1.9 though which source I got from https://git.devuan.org/jaretcantu/eudev. So that is why I would like to try to update that to at least eudev 3.0 on your tarball site.

I am closing this issue to make your issue tracking cleaner.
