### ISSUE TITLE
build fails with glibc-2.25 and gcc 6.3.0

### ISSUE THREAD

**Issue by CallMeFoxie** [gentoo/eudev#143]
Hi, using the latest release:
running autogen.sh and then ./configure --disable-selinux and then trying to compile with make:

fileio.c: In function 'read_one_line_file':
fileio.c:61:16: error: 'LINE_MAX' undeclared (first use in this function)
         char t[LINE_MAX], *c;

this happens in multiple files (6 or so) where limits.h is not included - and __USE_POSIX2 macro is not defined/set. Am I doing something wrong or is there an official way how to compile this? Using latest glibc-2.25 and gcc 6.3.0

Thanks
Ashley

**Comment by blueness** [comment]
Thanks, I haven't tested with the newer glibc/gcc, so I'll look into that.

**Comment by blueness** [comment]
Sorry for the delay.  I did test but found that it worked for me, so I waited until the rest Gentoo caught up with gcc-6.4.0 and glibc-2.25.  We stabilized those over a month ago and no one has hit this problem.  I'm not surprised though because LINE_MAX is defined through <limits.h>. 

Try this on your system

echo -e "#include <stdio.h>\n#include <limits.h>\nint main() { printf(\"%d\", LINE_MAX); }" > /tmp/limit_test.c ; gcc -o /tmp/limit_test /tmp/limit_test.c ; /tmp/limit_test

If you get a failure, check your system.  If you get success but you  are still hitting the bug with eudev, then reopen this bug because something more subtle might be going on.
